### ISSUE TITLE
Can`t download models with git lfs

### ISSUE THREAD

**Issue by nikelborm** [extnike/face_emotion_recognition#1]
When I trying to load your repo, i get following error:
```This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.```

```
pi@raspberrypi:~ $ git clone https://github.com/extnike/face_emotion_recognition.git
Cloning into 'face_emotion_recognition'...
remote: Enumerating objects: 241, done.
remote: Counting objects: 100% (241/241), done.
remote: Compressing objects: 100% (203/203), done.
remote: Total 241 (delta 87), reused 162 (delta 32), pack-reused 0
Receiving objects: 100% (241/241), 20.94 MiB | 1.32 MiB/s, done.
Resolving deltas: 100% (87/87), done.
Downloading _models/emotion_classification/checkpoint (83 B)
Error downloading object: _models/emotion_classification/checkpoint (6d0458d): Smudge error: Error downloading _models/emotion_classification/checkpoint (6d0458dab5529e88701397360fdee89ee78ce04dc8800170a765ad4dd473f31c): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /home/pi/face_emotion_recognition/.git/lfs/logs/20211208T221609.913854585.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: _models/emotion_classification/checkpoint: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Could you please post your repo with normal files or trained models files to google drive or mega or dropbox or something.
It will be appreciated so much for me.
Please, I really need it

**Comment by nikelborm** [comment]
@extnike

**Comment by nikelborm** [comment]
Previous error i think is the reason of this behaviour:
```
pi@raspberrypi:~/face_emotion_recognition $ python3 webcam_fer.py
Traceback (most recent call last):
  File "webcam_fer.py", line 3, in <module>
    from _models.vgg_fer import VGGFerModel
  File "/home/pi/face_emotion_recognition/_models/vgg_fer.py", line 1
    version https://git-lfs.github.com/spec/v1
                ^
SyntaxError: invalid syntax
```

**Comment by nikelborm** [comment]
Here is [solution](https://stackoverflow.com/a/68113604) for it, but only you can do it
