### ISSUE TITLE
Error while accessing the VGG Model

### ISSUE THREAD

**Issue by Mariyam73** [extnike/face_emotion_recognition#2]
@extnike 

I get the following error while running the code:
Traceback (most recent call last):
  File "video_fer.py", line 4, in <module>                                                                                
    from _models.vgg_fer import VGGFerModel                                                                               
  File "~\face_emotion_recognition-main\_models\vgg_fer.py", line 1
    version https://git-lfs.github.com/spec/v1                                                                            
            ^
SyntaxError: invalid syntax

How do I access the model?

**Comment by laviniasalicchi** [comment]
Hi, did you find a solution at the end?
